{
 "title": "datname",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datname",
    "query": {
     "query": "label_values(pg_database_size_bytes,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "db state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sizes of all DBs",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=~\"$datname\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoints Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoints_timed_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Reads Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time for executing SQL statements",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_active_time_seconds_total{datname=~\"$datname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pg_stat_database_blks_hit{datname=~\"$datname\"} \r\n/ \r\n(pg_stat_database_blks_hit{datname=~\"$datname\"} + pg_stat_database_blks_read{datname=~\"$datname\"})\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rows Returned",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_returned[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table Size (transactions table)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_table_size_bytes{relname=\"transactions\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go GC Pause: 50% percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of blocks by type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 31 },
   "targets": [
    {
     "expr": "sum(pg_locks_count{datname=~\"$datname\"}) by (mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of active connections to db",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=~\"$datname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Commit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_active_time_seconds_total{datname=~\"$datname\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}