{
 "title": "Node Exporter metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_load1,instance)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(node_filesystem_size_bytes,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU iowait %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"iowait\",instance=~\"$instance\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Transmit (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo\",instance=~\"$instance\"}[5m]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Load Average (15m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - node_filesystem_avail_bytes{device=~\"$device\", instance=~\"$instance\", fstype!~\"tmpfs|squashfs\"} / node_filesystem_size_bytes{device=~\"$device\", instance=~\"$instance\", fstype!~\"tmpfs|squashfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$instance\"} - node_boot_time_seconds{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo\",instance=~\"$instance\"}[5m]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Core",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "100 * (1 - rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Free Space (GiB)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=~\"$device\", instance=~\"$instance\", fstype!~\"tmpfs|squashfs\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Free Space per Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 23 },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{fstype!~\"tmpfs|squashfs\",instance=~\"$instance\"}) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 28 },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / node_memory_MemTotal_bytes{instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}