{
 "title": "Reddit Metrics Dashboard",
 "tags": [
  "reddit",
  "prometheus",
  "social-media"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "10s,30s,1m,5m,10m,30m,1h" },
   {
    "name": "subreddit",
    "query": "label_values(reddit_subscribers, subreddit)"
   }
  ]
 },
 "panels": [
  {
   "title": "Reddit exporter stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "reddit_exporter_up{subreddit=~\"$subreddit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comments Distribution",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "reddit_avg_comments{subreddit=~\"$subreddit\"}",
     "legendFormat": "{{subreddit}} - Avg Comments"
    },
    {
     "expr": "reddit_top_post_comments{subreddit=~\"$subreddit\"}",
     "legendFormat": "{{subreddit}} - Top Post Comments"
    }
   ]
  },
  {
   "title": "Avg score of posts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reddit_avg_score{subreddit=~\"$subreddit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Post Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "reddit_top_post_score{subreddit=~\"$subreddit\"}",
     "legendFormat": "{{subreddit}} - Top Post Score"
    },
    {
     "expr": "rate(reddit_top_post_score{subreddit=~\"$subreddit\"}[$interval])",
     "legendFormat": "{{subreddit}} - Score Rate of Change"
    }
   ]
  },
  {
   "title": "Num of posts for last survey",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "reddit_posts_last_fetch{subreddit=~\"$subreddit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reddit Exporter Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reddit_exporter_up", "legendFormat": "Exporter Up" },
    {
     "expr": "time() - reddit_exporter_last_scrape_unix",
     "legendFormat": "Seconds Since Last Scrape"
    }
   ]
  },
  {
   "title": "Subreddit subscribers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reddit_subscribers{subreddit=~\"$subreddit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Subscribers (Stat)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "reddit_subscribers{subreddit=~\"$subreddit\"}",
     "legendFormat": "{{subreddit}}"
    }
   ]
  },
  {
   "title": "Title Lengths",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reddit_post_title_length_avg{subreddit=~\"$subreddit\"}",
     "legendFormat": "{{subreddit}} - Avg Length"
    }
   ]
  },
  {
   "title": "Upvotes vs Downvotes Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "reddit_total_upvotes{subreddit=~\"$subreddit\"} / (reddit_total_downvotes{subreddit=~\"$subreddit\"} + 1)",
     "legendFormat": "{{subreddit}} - Upvote/Downvote Ratio"
    },
    {
     "expr": "increase(reddit_total_upvotes{subreddit=~\"$subreddit\"}[$interval])",
     "legendFormat": "{{subreddit}} - Upvote Increase ($interval)"
    }
   ]
  },
  {
   "title": "Objects collected during gc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Post Score Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "avg_over_time(reddit_avg_score{subreddit=~\"$subreddit\"}[$interval])",
     "legendFormat": "{{subreddit}} - Avg Score ($interval)"
    },
    {
     "expr": "deriv(reddit_avg_score{subreddit=~\"$subreddit\"}[$interval])",
     "legendFormat": "{{subreddit}} - Score Derivative"
    }
   ]
  },
  {
   "title": "Engagement Correlation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (subreddit) (reddit_avg_score{subreddit=~\"$subreddit\"} * reddit_avg_comments{subreddit=~\"$subreddit\"})",
     "legendFormat": "{{subreddit}} - Score×Comments Product"
    },
    {
     "expr": "clamp_max(reddit_active_users{subreddit=~\"$subreddit\"} / 100, 1000)",
     "legendFormat": "{{subreddit}} - Normalized Active Users"
    }
   ]
  }
 ]
}